### ISSUE TITLE
ModuleNotFoundError: No module named 'remarkable_fs'

### ISSUE THREAD

**Issue by YannGohgi** [naclander/Calibre-Remarkable-Device-Driver-Plugin#17]
First: Thanks for the work!

I installed the Plugin via the Developer Way. The Output of create-plugin-zip.sh is all positive, except of the depreciation of python2 stuff. All necessities get made.
Yet Calibre doesn't find remarkable_fs.

`calibre-customize -b ./ && calibre-debug -g 
Plugin updated: Remarkable Plugin (1, 2, 3)
calibre 5.44  embedded-python: True is64bit: True
Linux-4.15.0-20-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '4.15.0-20-generic', '#21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018')
Python 3.8.5
Interface language: de
Successfully initialized third party plugins: Remarkable Plugin (1, 2, 3)
Turning on automatic hidpi scaling
QApplication: invalid style override 'gtk' passed, ignoring it.
	Available styles: Windows, Fusion
devicePixelRatio: 1.0
logicalDpi: 96.18934911242603 x 96.30331753554502
physicalDpi: 124.5670498084291 x 124.66257668711656
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.15] db initialized
[0.15] Constructing main UI...
Startup method for device RemarkablePlugin threw exception
Traceback (most recent call last):
  File "calibre/gui2/device.py", line 411, in run_startup
  File "calibre_plugins.remarkable_plugin.__init__", line 33, in startup
    import remarkable_fs
ModuleNotFoundError: No module named 'remarkable_fs'
Error during device detection for <calibre_plugins.remarkable_plugin.RemarkablePlugin object at 0x7fb51deeb490>:
Traceback (most recent call last):
  File "calibre/gui2/device.py", line 326, in detect_device
  File "calibre_plugins.remarkable_plugin.__init__", line 50, in detect_managed_devices
    if self.seen_device:
AttributeError: 'RemarkablePlugin' object has no attribute 'seen_device'
[1.41] main UI initialized...
[1.41] Hiding splash screen
Starting QuickView
[1.76] splash screen hidden
[1.77] Started up in 1.77 seconds with 38 books
Error during device detection for <calibre_plugins.remarkable_plugin.RemarkablePlugin object at 0x7fb51deeb490>:
Traceback (most recent call last):
  File "calibre/gui2/device.py", line 326, in detect_device
  File "calibre_plugins.remarkable_plugin.__init__", line 50, in detect_managed_devices
    if self.seen_device:
AttributeError: 'RemarkablePlugin' object has no attribute 'seen_device'
Error during device detection for <calibre_plugins.remarkable_plugin.RemarkablePlugin object at 0x7fb51deeb490>:
Traceback (most recent call last):
  File "calibre/gui2/device.py", line 326, in detect_device
  File "calibre_plugins.remarkable_plugin.__init__", line 50, in detect_managed_devices
    if self.seen_device:
AttributeError: 'RemarkablePlugin' object has no attribute 'seen_device'
`
Thanks

**Comment by YannGohgi** [comment]
Sorry for the formatting. First timer.
