### ISSUE TITLE
Doesn't work on M1 Macbook

### ISSUE THREAD

**Issue by bhirsch42** [naclander/Calibre-Remarkable-Device-Driver-Plugin#6]
When running with `calibre-customize -b`, loading the plugin on calibre startup fails at `import remarkable_fs` because it can't find the package.

When running with the generated zip file, it fails with:
```
ImportError: cannot import name 'asn1' from 'cryptography.hazmat.bindings._rust' (unknown location)
```

...like in #2.

When running with the pycrypt version from #2, it gets to here:
```
➜  Calibre-Remarkable-Device-Driver-Plugin git:(main) ✗ calibre-debug -g
calibre 5.29  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Remarkable Plugin (1, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 149.00000223775552 x 149.0000022377555
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
> /Users/benhirsch/repos/Calibre-Remarkable-Device-Driver-Plugin/calibre_plugins.remarkable_plugin.__init__(34)startup()
-> import remarkable_fs
(Pdb)
```
...and then hangs forever.

**Comment by bhirsch42** [comment]
I suspect it has something to do with the fact that Calibre is on Python 3.8.5, which is incompatible with M1 Macbooks.

**Comment by bhirsch42** [comment]
I removed some trailing slashes from the config and it hangs again.

**Comment by naclander** [comment]
The error seems to be here:
```
Startup method for device RemarkablePlugin threw exception
Traceback (most recent call last):
  File "calibre/gui2/device.py", line 378, in run_startup
  File "calibre_plugins.remarkable_plugin.__init__", line 34, in startup
    import remarkable_fs
  File "calibre_plugins.remarkable_plugin.__init__", line 34, in startup
    import remarkable_fs
  File "bdb.py", line 88, in trace_dispatch
  File "bdb.py", line 113, in dispatch_line
bdb.BdbQuit
```

Somehow its failing to import `remarkable_fs` which is the biggest issue so far ( for others as well ) with this plugin.

**Comment by yoiang** [comment]
If I understand correctly from reading through this and **cryptography**'s similar issues its that `pip` is gathering versions of **cryptography** that are not compatible with the version of **Python** included with **calibre**, is that a correct summary?
